const DB_NAME="reconciliation_app_db_v3";const DB_VERSION=1;const STATE_STORE="state";const IMAGE_STORE="images";const STATE_KEY="current";const LOCAL_KEY="reconciliation_state_v3";let db=null;let state=defaultState();let saveTimer=null;
const el={appTitle:document.getElementById("appTitle"),incomeNameLabel:document.getElementById("incomeNameLabel"),incomeMoneyLabel:document.getElementById("incomeMoneyLabel"),expenseNameLabel:document.getElementById("expenseNameLabel"),expenseMoneyLabel:document.getElementById("expenseMoneyLabel"),statusLabel:document.getElementById("statusLabel"),rows:document.getElementById("rows"),totalIncome:document.getElementById("totalIncome"),totalExpense:document.getElementById("totalExpense"),difference:document.getElementById("difference"),diffBox:document.getElementById("diffBox"),topStatus:document.getElementById("topStatus"),topStatusText:document.getElementById("topStatusText"),topStatusSub:document.getElementById("topStatusSub"),saveState:document.getElementById("saveState"),fontScale:document.getElementById("fontScale")};
function defaultState(){return{appTitle:"收支核对",compact:false,fontScale:100,labels:{incomeName:"姓名",incomeMoney:"金额",expenseName:"姓名",expenseMoney:"金额",status:"状态"},rows:[row("微信","100","支付宝","100"),row("现金","250","银行卡","250"),row("客户A","450","供应商A","400"),row("","","","")]}};
function row(incomeName="",incomeAmount="",expenseName="",expenseAmount=""){return{id:crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),incomeName,incomeAmount,expenseName,expenseAmount,imageId:null,imageName:""}}
function openDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const database=request.result;if(!database.objectStoreNames.contains(STATE_STORE))database.createObjectStore(STATE_STORE);if(!database.objectStoreNames.contains(IMAGE_STORE))database.createObjectStore(IMAGE_STORE)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function dbGet(store,key){return new Promise((resolve,reject)=>{if(!db)return resolve(null);const tx=db.transaction(store,"readonly");const req=tx.objectStore(store).get(key);req.onsuccess=()=>resolve(req.result??null);req.onerror=()=>reject(req.error)})}
function dbSet(store,key,value){return new Promise((resolve,reject)=>{if(!db)return resolve();const tx=db.transaction(store,"readwrite");tx.objectStore(store).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
function dbDelete(store,key){return new Promise((resolve,reject)=>{if(!db)return resolve();const tx=db.transaction(store,"readwrite");tx.objectStore(store).delete(key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function loadState(){try{db=await openDB();const stored=await dbGet(STATE_STORE,STATE_KEY);if(stored)return normalizeState(stored)}catch(error){console.warn("IndexedDB 不可用，使用 localStorage。",error)}try{const local=localStorage.getItem(LOCAL_KEY);if(local)return normalizeState(JSON.parse(local))}catch(error){console.warn("localStorage 读取失败。",error)}return defaultState()}
function normalizeState(input){const fallback=defaultState();return{appTitle:input.appTitle||fallback.appTitle,compact:Boolean(input.compact),fontScale:Number(input.fontScale||100),labels:{...fallback.labels,...(input.labels||{})},rows:Array.isArray(input.rows)&&input.rows.length?input.rows.map(r=>({id:r.id||row().id,incomeName:r.incomeName??"",incomeAmount:r.incomeAmount??"",expenseName:r.expenseName??"",expenseAmount:r.expenseAmount??"",imageId:r.imageId??null,imageName:r.imageName??""})):fallback.rows}}
function persistSoon(){el.saveState.textContent="保存中…";el.saveState.style.color="#ca8a04";clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{localStorage.setItem(LOCAL_KEY,JSON.stringify(state));await dbSet(STATE_STORE,STATE_KEY,state);el.saveState.textContent="已保存";el.saveState.style.color="#16a34a"}catch(error){console.error(error);el.saveState.textContent="保存失败";el.saveState.style.color="#dc2626"}},180)}
function parseMoney(value){if(value===""||value===null||value===undefined)return 0;const clean=String(value).replace(/[^\d.-]/g,"");const n=Number(clean);return Number.isFinite(n)?n:NaN}
function formatMoney(value){return Number(value||0).toLocaleString("zh-CN",{maximumFractionDigits:2})}
function getRowStatus(r){const income=parseMoney(r.incomeAmount);const expense=parseMoney(r.expenseAmount);if(!Number.isFinite(income)||!Number.isFinite(expense))return{type:"mismatch",text:"错误"};const hasIncome=String(r.incomeAmount).trim()!=="";const hasExpense=String(r.expenseAmount).trim()!=="";if(!hasIncome&&!hasExpense)return{type:"waiting",text:"待输入"};if(!hasIncome||!hasExpense)return{type:"waiting",text:"待匹配"};if(income===expense)return{type:"match",text:"一致"};return{type:"mismatch",text:`差 ${formatMoney(income-expense)}`}}
function totals(){let invalid=false;const result=state.rows.reduce((acc,r)=>{const income=parseMoney(r.incomeAmount);const expense=parseMoney(r.expenseAmount);if(!Number.isFinite(income)||!Number.isFinite(expense)){invalid=true;return acc}acc.income+=income;acc.expense+=expense;return acc},{income:0,expense:0});result.diff=result.income-result.expense;result.invalid=invalid;return result}
function escapeHtml(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function render(){document.documentElement.style.setProperty("--font-scale",state.fontScale/100);document.body.classList.toggle("compact",state.compact);el.appTitle.textContent=state.appTitle;el.incomeNameLabel.textContent=state.labels.incomeName;el.incomeMoneyLabel.textContent=state.labels.incomeMoney;el.expenseNameLabel.textContent=state.labels.expenseName;el.expenseMoneyLabel.textContent=state.labels.expenseMoney;el.statusLabel.textContent=state.labels.status;el.fontScale.value=state.fontScale;el.rows.innerHTML=state.rows.map((r,idx)=>{const status=getRowStatus(r);const hasImage=Boolean(r.imageId);return `<article class="recon-row" data-row-id="${r.id}"><div class="cell income-cell" data-label="${escapeHtml(state.labels.incomeName)}"><input value="${escapeHtml(r.incomeName)}" placeholder="收入来源" oninput="updateRow(${idx}, 'incomeName', this.value)" /></div><div class="cell income-cell" data-label="${escapeHtml(state.labels.incomeMoney)}"><input class="amount-input" type="number" inputmode="decimal" value="${escapeHtml(r.incomeAmount)}" placeholder="0" oninput="updateRow(${idx}, 'incomeAmount', this.value)" /></div><div class="cell expense-cell" data-label="${escapeHtml(state.labels.expenseName)}"><input value="${escapeHtml(r.expenseName)}" placeholder="支出去向" oninput="updateRow(${idx}, 'expenseName', this.value)" /></div><div class="cell expense-cell" data-label="${escapeHtml(state.labels.expenseMoney)}"><input class="amount-input" type="number" inputmode="decimal" value="${escapeHtml(r.expenseAmount)}" placeholder="0" oninput="updateRow(${idx}, 'expenseAmount', this.value)" /></div><div class="cell status-cell" data-label="${escapeHtml(state.labels.status)}"><span class="status-pill ${status.type}">${escapeHtml(status.text)}</span><div class="row-actions"><button class="icon-btn ${hasImage?"image-on":""}" onclick="pickImage(${idx})" title="上传图片">图</button><button class="icon-btn" onclick="viewImage(${idx})" title="查看图片" ${hasImage?"":"disabled"}>看</button><button class="icon-btn danger" onclick="deleteRow(${idx})" title="删除">×</button></div><input id="imageInput-${idx}" type="file" accept="image/*" hidden onchange="storeImage(${idx}, this.files[0])" /></div></article>`}).join("");renderTotals()}
function renderTotals(){const t=totals();el.totalIncome.textContent=formatMoney(t.income);el.totalExpense.textContent=formatMoney(t.expense);el.difference.textContent=formatMoney(t.diff);const allEmpty=state.rows.every(r=>!String(r.incomeAmount).trim()&&!String(r.expenseAmount).trim());let status="success",text="成功",sub="收入与支出一致";if(t.invalid){status="failed";text="失败";sub="存在无效金额"}else if(allEmpty){status="waiting";text="待输入";sub="请填写收入与支出"}else if(t.diff!==0){status="failed";text="失败";sub=`差额 ${formatMoney(t.diff)}`}el.topStatus.className=`top-status ${status}`;el.topStatusText.textContent=text;el.topStatusSub.textContent=sub;el.diffBox.className=status==="success"?"success":"failed"}
window.updateRow=function(index,field,value){state.rows[index][field]=value;persistSoon();renderTotals();if(field.includes("Amount")){const rowEl=document.querySelectorAll(".recon-row")[index];const statusEl=rowEl?.querySelector(".status-pill");if(statusEl){const s=getRowStatus(state.rows[index]);statusEl.className=`status-pill ${s.type}`;statusEl.textContent=s.text}}};
window.deleteRow=async function(index){const r=state.rows[index];if(!confirm("删除这一行？"))return;if(r.imageId)await dbDelete(IMAGE_STORE,r.imageId);state.rows.splice(index,1);if(state.rows.length===0)state.rows.push(row());persistSoon();render()};
window.pickImage=function(index){document.getElementById(`imageInput-${index}`).click()};
window.storeImage=async function(index,file){if(!file)return;const imageId=state.rows[index].imageId||(crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()));await dbSet(IMAGE_STORE,imageId,file);state.rows[index].imageId=imageId;state.rows[index].imageName=file.name||"图片";persistSoon();render()};
window.viewImage=async function(index){const imageId=state.rows[index].imageId;if(!imageId)return;const blob=await dbGet(IMAGE_STORE,imageId);if(!blob){alert("图片不存在。");return}const url=URL.createObjectURL(blob);const img=document.getElementById("previewImage");img.src=url;document.getElementById("imageDialog").showModal()};
document.getElementById("closeImageDialog").addEventListener("click",()=>{const img=document.getElementById("previewImage");if(img.src)URL.revokeObjectURL(img.src);document.getElementById("imageDialog").close()});
document.getElementById("addRowBtn").addEventListener("click",()=>{state.rows.push(row());persistSoon();render();setTimeout(()=>window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"}),80)});
document.getElementById("toggleDensityBtn").addEventListener("click",()=>{state.compact=!state.compact;document.getElementById("toggleDensityBtn").textContent=state.compact?"舒适模式":"紧凑模式";persistSoon();render()});
el.fontScale.addEventListener("input",()=>{state.fontScale=Number(el.fontScale.value);persistSoon();render()});
function bindEditable(elm,path){elm.addEventListener("blur",()=>{const value=elm.textContent.trim();if(path==="appTitle")state.appTitle=value||"收支核对";if(path.startsWith("labels.")){const key=path.split(".")[1];state.labels[key]=value||defaultState().labels[key]}persistSoon();render()})}
bindEditable(el.appTitle,"appTitle");bindEditable(el.incomeNameLabel,"labels.incomeName");bindEditable(el.incomeMoneyLabel,"labels.incomeMoney");bindEditable(el.expenseNameLabel,"labels.expenseName");bindEditable(el.expenseMoneyLabel,"labels.expenseMoney");bindEditable(el.statusLabel,"labels.status");
document.getElementById("backupBtn").addEventListener("click",()=>{const payload={exportedAt:new Date().toISOString(),state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});downloadBlob(blob,`收支核对备份-${new Date().toISOString().slice(0,10)}.json`)});
document.getElementById("importBackupInput").addEventListener("change",async(event)=>{const file=event.target.files?.[0];if(!file)return;try{const text=await file.text();const payload=JSON.parse(text);state=normalizeState(payload.state||payload);persistSoon();render();alert("导入成功。")}catch(error){alert("导入失败，请检查备份文件。")}finally{event.target.value=""}});
document.getElementById("saveImageBtn").addEventListener("click",saveReportImage);
function drawRoundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+r,y,r);ctx.closePath()}
async function saveReportImage(){const t=totals();const rows=state.rows;const width=1400;const rowH=62;const headerH=220;const totalH=118;const height=headerH+(rows.length*rowH)+totalH+80;const scale=Math.max(2,window.devicePixelRatio||2);const canvas=document.createElement("canvas");canvas.width=width*scale;canvas.height=height*scale;const ctx=canvas.getContext("2d");ctx.scale(scale,scale);ctx.fillStyle="#eef2f8";ctx.fillRect(0,0,width,height);ctx.fillStyle="#ffffff";drawRoundRect(ctx,40,40,width-80,height-80,32);ctx.fill();ctx.fillStyle="#0f172a";ctx.font="bold 56px Microsoft YaHei, PingFang SC, Arial";ctx.fillText(state.appTitle||"收支核对",78,116);ctx.font="bold 24px Microsoft YaHei, PingFang SC, Arial";ctx.fillStyle="#64748b";ctx.fillText(new Date().toLocaleString("zh-CN"),80,154);const ok=!t.invalid&&t.diff===0;ctx.fillStyle=ok?"#16a34a":"#dc2626";drawRoundRect(ctx,width-278,74,200,64,32);ctx.fill();ctx.fillStyle="#ffffff";ctx.font="bold 30px Microsoft YaHei, PingFang SC, Arial";ctx.fillText(ok?"成功":"失败",width-210,116);const x=78;let y=190;const col=[x,x+270,x+440,x+710,x+880];const colW=[270,170,270,170,300];ctx.fillStyle="#e2e8f0";drawRoundRect(ctx,x,y,width-156,52,18);ctx.fill();const headers=[state.labels.incomeName,state.labels.incomeMoney,state.labels.expenseName,state.labels.expenseMoney,state.labels.status];ctx.fillStyle="#0f172a";ctx.font="bold 24px Microsoft YaHei, PingFang SC, Arial";headers.forEach((h,i)=>ctx.fillText(h,col[i]+18,y+34));y+=64;ctx.font="bold 23px Microsoft YaHei, PingFang SC, Arial";rows.forEach((r,i)=>{const status=getRowStatus(r);ctx.fillStyle=i%2===0?"#f8fafc":"#ffffff";drawRoundRect(ctx,x,y,width-156,52,14);ctx.fill();ctx.fillStyle="#0891b2";ctx.fillText(r.incomeName||"-",col[0]+18,y+34);ctx.textAlign="right";ctx.fillText(formatMoney(parseMoney(r.incomeAmount)),col[1]+colW[1]-18,y+34);ctx.textAlign="left";ctx.fillStyle="#c2410c";ctx.fillText(r.expenseName||"-",col[2]+18,y+34);ctx.textAlign="right";ctx.fillText(formatMoney(parseMoney(r.expenseAmount)),col[3]+colW[3]-18,y+34);ctx.textAlign="left";ctx.fillStyle=status.type==="match"?"#16a34a":(status.type==="waiting"?"#ca8a04":"#dc2626");ctx.fillText(status.text,col[4]+18,y+34);y+=rowH});y+=20;ctx.fillStyle="#0f172a";drawRoundRect(ctx,x,y,width-156,78,22);ctx.fill();ctx.font="bold 28px Microsoft YaHei, PingFang SC, Arial";ctx.fillStyle="#ffffff";ctx.fillText(`收入：${formatMoney(t.income)}`,x+30,y+50);ctx.fillText(`支出：${formatMoney(t.expense)}`,x+430,y+50);ctx.fillStyle=ok?"#86efac":"#fca5a5";ctx.fillText(`差额：${formatMoney(t.diff)}`,x+830,y+50);canvas.toBlob(async(blob)=>{if(!blob)return alert("保存图片失败。");const filename=`收支核对-${new Date().toISOString().slice(0,10)}.png`;const file=new File([blob],filename,{type:"image/png"});if(navigator.canShare&&navigator.canShare({files:[file]})){try{await navigator.share({files:[file],title:"收支核对"});return}catch(error){}}downloadBlob(blob,filename)},"image/png",0.96)}
function downloadBlob(blob,filename){const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
window.addEventListener("pagehide",()=>{try{localStorage.setItem(LOCAL_KEY,JSON.stringify(state))}catch(error){}});
async function init(){state=await loadState();render();document.getElementById("toggleDensityBtn").textContent=state.compact?"舒适模式":"紧凑模式";if("serviceWorker"in navigator){navigator.serviceWorker.register("service-worker.js")}}init();
